version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Setting up node"
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - \. /home/ec2-user/.bashrc
      - \. /home/ec2-user/.nvm/nvm.sh
      - nvm alias default v12.7.0
      - nvm install v12.7.0
      - nvm use v12.7.0
      - echo "Node setup complete"
  pre_build:
    commands:
      - echo 'Creating directories'
      - mkdir -p /home/ec2-user/app/logs
      - echo "Installing dependencies"
      - npm ci
  build:
    commands:
      - echo "Building app/running tests"
        # - npm test
    post_build:
      commands:
        - echo "Build completed"
    artifacts:
      files:
        - '**/*'
